[params]
    [[params.leaders]]
    name = "Justice Diven"
    info_url = "https://www.linkedin.com/in/justice-diven-4483724/"
    title = "Member Leader"
    company = "BP Onshore Lower 48"
    profile_picture_filename = "justice-diven-profile-image.png"

    [[params.leaders]]
    name = "Melissa Dochter"
    info_url = "https://www.linkedin.com/in/melissa-dochter-8b558b26/"
    title = "Member Leader"
    company = "Schneider Electric"
    profile_picture_filename = "melissa-dochter-profile-image.png"

    [[params.leaders]]
    name = "Ron Gill"
    info_url = "https://www.linkedin.com/in/ron-gill-atf-hsme-cmfge-9aa77b1b/"
    title = "Member Leader"
    company = "The Boeing Company (Retired)"
    profile_picture_filename = "ron-gill-profile-image.png"
