[params]
    [[params.leaders]]
    name = "Vesna Cota"
    info_url = "https://www.linkedin.com/in/vesnacota/"
    title = "Member Leader"
    company = "Tyco Electronics Canada, TE Connectivity, Automotive (retired)"

    [[params.leaders]]
    name = "Melissa Dochter"
    info_url = "https://www.linkedin.com/in/melissa-dochter-8b558b26/"
    title = "Member Leader"
    company = "Schneider Electric"

    [[params.leaders]]
    name = "Ron Gill"
    info_url = "https://www.linkedin.com/in/ron-gill-atf-hsme-cmfge-9aa77b1b/"
    title = "Member Leader"
    company = "The Boeing Company (Retired)"

    [[params.leaders]]
    name = "William Sniadack"
    info_url = "https://www.linkedin.com/in/william-sniadack-6b6324123/"
    title = "Member Leader"
    company = "Neles USA, Inc."

    [[params.leaders]]
    name = "Zachary Zichi"
    info_url = "https://www.linkedin.com/in/zachary-zichi-b33915181/"
    title = "SME Staff Liaison"
    company = "SME"
